### ISSUE TITLE
INPUT OUTPUT INTERFACE

### ISSUE THREAD

**Issue by NLPCL** [nlpcl-lab/sentential_argument_generation#1]
hi, @ddehun, I am doing the end-of-the-year check up.
the results format is clear.
Yet, I find that it is confounding how I can put a sentence that I choose
and get the result.

if possible, please put the material in the README file,
such as "python main.py --input_sentence input_file.txt --ouput output_file.txt"

thanks, yours sincerely, Yang

**Comment by ddehun** [comment]
Hi. Thank you for your good suggestion. I'll include the interface for plan text asap.
